new create_order method
fremantle-capital/ex_binance pull request #36
Opened 2020-12-29 14:06 UTC by arturictus

2020-12-29 17:23 UTC, rupurt requested changes

2020-12-29 17:23 UTC, rupurt commented on mix.exs
> -      version: "0.0.5",
:scissors: I like to do this in a separate PR

2020-12-29 17:23 UTC, rupurt commented on lib/ex_binance/timestamp.ex
> +  def now(), do: System.os_time(:millisecond)
:+1:

2020-12-29 17:23 UTC, rupurt commented on lib/ex_binance/private.ex
> +  defdelegate create_order(
Can you add a test for this new function?

2020-12-29 17:23 UTC, rupurt commented on lib/ex_binance/rest/create_order.ex
>      |> parse_response()
How do you feel about calling the new function here so we share code paths?

2020-12-31 06:38 UTC, rupurt commented
@arturictus can you also rebase this PR? I've fixed up the test runner on CI

2021-01-04 10:39 UTC, arturictus commented
> @arturictus can you also rebase this PR? I've fixed up the test runner on CI

Hi @rupurt, I did not want to submit the PR yet I'm still working in on it and I will have to change few things to make it work with my project, those will be breaking changes.

I let you know when I have it ready and we can decide if the changes are suited for merge.

I'll try the new CI runner :)

2021-01-04 15:04 UTC, rupurt commented
No worries @arturictus. Thanks for the update.

2021-03-01 18:19 UTC, rupurt commented
Closing in favor of #43. Thanks for the initial idea in this PR @arturictus

2021-03-01 18:19 UTC, closed without merging